app-dev:
  build: containers/app-dev
  command: bash -c "cd /root/code/tob && boot dev"
  ports:
    - "80:8080"
    - "3000:3000"
    - "1337:1337"
  volumes:
    - ./code:/root/code
    - ~/.m2/:/m2
  links:
    - couchdb
couchdb:
  image: frodenas/couchdb
  ports:
    - "5984:5984"
  environment:
    - COUCHDB_USERNAME=tob
    - COUCHDB_PASSWORD=tobtob
    - COUCHDB_DBNAME=tob
  volumes:
    - /tmp/couchdb:/data