app-dev:
  build: containers/app-dev
  command: bash -c "cd /root/code/tob && boot dev"
  ports:
    - "3000:3000"
    - "1337:1337"
  volumes:
    - ./code:/root/code
    - ~/.m2/:/m2
  links:
    - redis
redis:
  image: redis
  ports:
    - "6379:6379"